% This file is part of the project NILM-Eval (https://github.com/beckel/nilm-eval).
% Licence: GPL 2.0 (http://www.gnu.org/licenses/gpl-2.0.html)
% Copyright: ETH Zurich, 2014
% Author: Romano Cicchetti

% returns a cell with all appliance names
function [cellWithAllApplianceNames] = getCellWithAllApplianceNames()

    cellWithAllApplianceNames = { ...
        'Electric Heater Bedroom', ...
        'Water Heater', ...
        'Oven', ...
        'TV', ...
        'Coffee Maker', ...
        'Electric Kettle', ...
        'Electric Heater Salong', ...
        'Microwave Oven', ...
        'Electric Heater Terrace', ...
        'Dishwasher', ...
        'Fridge', ...
        'Washing machine', ...
    };
    
end


